class RegisController < ApplicationController
  # 1. Rails 8 Authentication: Ensure a session exists
  # This comes from the 'Authenticated' concern generated by Rails 8
  before_action :resume_session 

  # 2. Staff-Only Authorization: Keep Patients out of the list/search
  before_action :require_management_access, only: [:index, :show, :edit, :update, :destroy]

  before_action :set_regi, only: %i[ show edit update destroy ]

  # GET /regis
  def index
    # Ransack stays exactly the same!
    @q = Regi.ransack(params[:q])
    @regis = @q.result(distinct: true).order("last_name, first_name, init, dob")
  end

  # GET /regis/1 or /regis/1.json
  def show
  end

  # GET /regis/new
  def new
    @regi = Regi.new
  end

  # GET /regis/1/edit
  def edit
  end

  # POST /regis or /regis.json
  def create
    @regi = Regi.new(regi_params)
    if @regi.save
      redirect_to regis_path, notice: "New Patient Registered..."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /regis/1 or /regis/1.json
  def update
    if @regi.update regi_params
      #@regi.update(p_name: "#{@regi.last_name}, #{@regi.first_name} #{@regi.init}")
      redirect_to regis_path, notice: "Patient Registration updated..."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /regis/1 or /regis/1.json
  def destroy
    @regi.destroy
    redirect_to regis_path, notice: "Patient Registration, records and charts all deleted..." 
  end

  private
  # This is your custom Role-Based "What-If" logic
  def require_management_access
    # If a user is logged in but is just a 'patient', kick them to the root
    unless Current.user.admin? || Current.user.manager?
      redirect_to root_path, alert: "You do not have permission to access patient records."
    end
  end

  def set_regi
    @regi = Regi.find(params[:id])
  end

  def regi_params
    params.require(:regi).permit(:last_name, :first_name, :init, :gender, :dob, :p_name, :age)
  end
end
